# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "CommandLineParser"; version = "2.9.1"; sha256 = "1sldkj8lakggn4hnyabjj1fppqh50fkdrr1k99d4gswpbk5kv582"; })
  (fetchNuGet { pname = "libLLVM"; version = "16.0.6"; sha256 = "0vmwdyids3bwjarnk308py1bhljv78pjbs7hk3ahkdamxf5mk4qs"; })
  (fetchNuGet { pname = "libLLVM.runtime.linux-arm64"; version = "16.0.6"; sha256 = "1ms9ibakm99wz2jb5qxn09xnqn5gycvzy960jlvmc0sfnvm7p0db"; })
  (fetchNuGet { pname = "libLLVM.runtime.linux-x64"; version = "16.0.6"; sha256 = "1bh1cayyqcqq7iwrjsac0634xwalh8a4pyc5p8g5a685sifmsh6y"; })
  (fetchNuGet { pname = "libLLVM.runtime.osx-arm64"; version = "16.0.6"; sha256 = "1z2k5zp79v78654dls02kdc4fr79kqv0l66mjq1kwn3d3gr1aqq2"; })
  (fetchNuGet { pname = "libLLVM.runtime.osx-x64"; version = "16.0.6"; sha256 = "102mw178vay3p4ps14avshj6m7xy24cf85vv8l8xbm0yl9b1p2v3"; })
  (fetchNuGet { pname = "libLLVM.runtime.win-x64"; version = "16.0.6"; sha256 = "0pnixcchip8j6xn08bjvfwqsqkl49jgc26w91ffk0gw954xixsgp"; })
  (fetchNuGet { pname = "LLVMSharp"; version = "16.0.0"; sha256 = "1qxsbdhhc0wii1vh0nfd8m8dyrzcfgw8178k8bf481s6n67wliig"; })
  (fetchNuGet { pname = "LLVMSharp.Interop"; version = "16.0.0"; sha256 = "0z56a2x0y0dhaca0qqpnlfidfb8kq29g6xd70brf6wajwkkb0nj4"; })
  (fetchNuGet { pname = "Samboy063.Tomlet"; version = "5.3.1"; sha256 = "0skh0pqr7rkhq96rfdz8gsqx13rvk9b4yxvfb53rsj0ipyyia38p"; })
]
